#
# Vivado (TM) v2013.4 (64-bit)
#
# build_ip.tcl: Tcl script for re-creating project 'axi_spdif_tx_v2_00_a'
#
# Generated by Vivado on Thu Feb 20 17:45:23 +1100 2014
# IP Build 208076 on Mon Dec  2 12:38:17 MST 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build_ip.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' variable setting below at the start of the script)
#
#    "C:/kutu/svn/kutu_data/XilinxIP/axi_spdif_tx_v2_00_a/axi_spdif_tx_v2_00_a.srcs/sources_1/dma_fifo.vhd"
#    "C:/kutu/svn/kutu_data/XilinxIP/axi_spdif_tx_v2_00_a/axi_spdif_tx_v2_00_a.srcs/sources_1/tx_package.vhd"
#    "C:/kutu/svn/kutu_data/XilinxIP/axi_spdif_tx_v2_00_a/axi_spdif_tx_v2_00_a.srcs/sources_1/tx_encoder.vhd"
#    "C:/kutu/svn/kutu_data/XilinxIP/axi_spdif_tx_v2_00_a/axi_spdif_tx_v2_00_a.srcs/sources_1/pl330_dma_fifo.vhd"
#    "C:/kutu/svn/kutu_data/XilinxIP/axi_spdif_tx_v2_00_a/axi_spdif_tx_v2_00_a.srcs/sources_1/axi_ctrlif.vhd"
#    "C:/kutu/svn/Hawk/trunk/XilinxIP/axi_spdif_tx_v2_00_a/sources/axi_spdif_tx.vhd"
#    "C:/kutu/svn/Hawk/trunk/XilinxIP/axi_spdif_tx_v2_00_a/component.xml"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir "../axi_spdif_tx_v2_00_a"

# Create project
create_project -force axi_spdif_tx_v2_00_a ../axi_spdif_tx_v2_00_a

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects axi_spdif_tx_v2_00_a]
set_property "board" "xilinx.com:zynq:zc706:1.1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources' fileset
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$orig_proj_dir/sources/dma_fifo.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/tx_package.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/tx_encoder.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/pl330_dma_fifo.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/axi_ctrlif.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/axi_spdif_tx.vhd"]"
]
add_files -norecurse -fileset $obj $files

# Set 'sources' fileset file properties for local files
set file "sources/dma_fifo.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/tx_package.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/tx_encoder.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/pl330_dma_fifo.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/axi_ctrlif.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/axi_spdif_tx.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "../../XilinxIP" $obj
set_property "top" "axi_spdif_tx" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "axi_spdif_tx" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]

ipx::package_project -root_dir {../axi_spdif_tx_v2_00_a}
set_property vendor {kutu.com.au} [ipx::current_core]
set_property library {kutu} [ipx::current_core]
set_property taxonomy {{/Kutu}} [ipx::current_core]
set_property vendor_display_name {Kutu Pty. Ltd.} [ipx::current_core]
set_property company_url {www.kutu.com.au} [ipx::current_core]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
ipx::create_xgui_files [ipx::current_core]
ipx::save_core [ipx::current_core]
update_ip_catalog -rebuild -repo_path ../../XilinxIP
ipx::check_integrity -quiet [ipx::current_core]
ipx::unload_core {kutu.com.au:kutu:axi_spdif_tx:1.0}

puts "INFO: Project created:axi_spdif_tx_v2_00_a"
