#
# Vivado (TM) v2017.4 (64-bit)
#
# build_ip.tcl: Tcl script for re-creating project 'hdmi_tx_v1_00_a'
#
# Generated by Vivado on Thu Feb 20 17:45:23 +1100 2014
# IP Build 208076 on Mon Dec  2 12:38:17 MST 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir "../hdmi_tx_v1_00_a"

# Create project
create_project -force hdmi_tx_v1_00_a ../hdmi_tx_v1_00_a

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects hdmi_tx_v1_00_a]
set_property "part" "xc7z010clg400-1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

set_property  ip_repo_paths  {./interfaces} [current_project]
update_ip_catalog

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources' fileset
add_files -norecurse sources/hdmi_display.vhd
add_files -norecurse sources/clock_gen_bufio.vhd
add_files -norecurse sources/TMDS_encoder.vhd
add_files -norecurse sources/hdmi_tx.vhd
add_files -norecurse sources/serializer.vhd
add_files -norecurse sources/frame_gen.vhd

set_property library hdmi_tx_v1_00_a [get_files sources/hdmi_display.vhd]
set_property library hdmi_tx_v1_00_a [get_files sources/clock_gen_bufio.vhd]
set_property library hdmi_tx_v1_00_a [get_files sources/TMDS_encoder.vhd]
set_property library hdmi_tx_v1_00_a [get_files sources/serializer.vhd]
set_property library hdmi_tx_v1_00_a [get_files sources/hdmi_tx.vhd]
set_property library hdmi_tx_v1_00_a [get_files sources/frame_gen.vhd]

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "../../XilinxIP" $obj
set_property "top" "hdmi_display" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "hdmi_display" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]

ipx::package_project -root_dir {../hdmi_tx_v1_00_a}

set_property vendor {kutu.com.au} [ipx::current_core]
set_property library {kutu} [ipx::current_core]
set_property taxonomy {{/Kutu}} [ipx::current_core]
set_property vendor_display_name {Kutu Pty. Ltd.} [ipx::current_core]
set_property company_url {http://www.kutu.com.au} [ipx::current_core]

set_property supported_families \
    {{virtex7}    {Production} \
     {qvirtex7}   {Production} \
     {kintex7}    {Production} \
     {kintex7l}   {Production} \
     {qkintex7}   {Production} \
     {qkintex7l}  {Production} \
     {artix7}     {Production} \
     {artix7l}    {Production} \
     {aartix7}    {Production} \
     {qartix7}    {Production} \
     {zynq}       {Production} \
     {qzynq}      {Production} \
     {azynq}      {Production}} \
  [ipx::current_core]

ipx::remove_bus_interface HDMI_CLK_N [ipx::current_core]
ipx::remove_bus_interface HDMI_CLK_P [ipx::current_core]
ipx::remove_bus_interface reset [ipx::current_core]
ipx::associate_bus_interfaces -busif s_axis_mm2s -clock s_axis_mm2s_aclk [ipx::current_core]
ipx::add_bus_parameter FREQ_HZ [ipx::get_bus_interfaces s_axis_mm2s_aclk -of_objects [ipx::current_core]]
set_property value 148500000 [ipx::get_bus_parameters FREQ_HZ -of_objects [ipx::get_bus_interfaces s_axis_mm2s_aclk -of_objects [ipx::current_core]]]

ipx::add_bus_interface HDMI [ipx::current_core]
set_property abstraction_type_vlnv kutu:user:hdmi_rtl:1.0 [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property bus_type_vlnv kutu:user:hdmi:1.0 [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property interface_mode master [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
ipx::add_port_map HDMI_D1_N [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D1_N [ipx::get_port_maps HDMI_D1_N -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_D0_N [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D0_N [ipx::get_port_maps HDMI_D0_N -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_CLK_P [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_CLK_P [ipx::get_port_maps HDMI_CLK_P -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_CLK_N [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_CLK_N [ipx::get_port_maps HDMI_CLK_N -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_D2_P [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D2_P [ipx::get_port_maps HDMI_D2_P -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_D1_P [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D1_P [ipx::get_port_maps HDMI_D1_P -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_D2_N [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D2_N [ipx::get_port_maps HDMI_D2_N -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::add_port_map HDMI_D0_P [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]
set_property physical_name HDMI_D0_P [ipx::get_port_maps HDMI_D0_P -of_objects [ipx::get_bus_interfaces HDMI -of_objects [ipx::current_core]]]
ipx::create_xgui_files [ipx::current_core]

ipx::save_core [ipx::current_core]
# update_ip_catalog -rebuild -repo_path ../../XilinxIP
ipx::check_integrity -quiet [ipx::current_core]
ipx::unload_core {kutu.com.au:kutu:hdmi_tx:1.0}
