#
# Vivado (TM) v2013.4 (64-bit)
#
# build_ip.tcl: Tcl script for re-creating project 'axi_clkgen_v2_00_a'
#
# Generated by Vivado on Thu Feb 20 17:45:23 +1100 2014
# IP Build 208076 on Mon Dec  2 12:38:17 MST 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir "../axi_clkgen_v2_00_a"

# Create project
create_project -force axi_clkgen_v2_00_a ../axi_clkgen_v2_00_a

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects axi_clkgen_v2_00_a]
set_property "board" "xilinx.com:zynq:zc706:1.1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources' fileset
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$orig_proj_dir/sources/vhdl/axi_clkgen.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/address_decoder.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/axi_lite_ipif.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/family_support.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/ipif_pkg.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/pselect_f.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/slave_attachment.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/vhdl/proc_common_pkg.vhd"]"\
 "[file normalize "$orig_proj_dir/sources/verilog/cf_clkgen.v"]"\
 "[file normalize "$orig_proj_dir/sources/verilog/user_logic2.v"]"
]
add_files -norecurse -fileset $obj $files

# Set 'sources' fileset file properties for local files
set file "sources/vhdl/address_decoder.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/axi_clkgen.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/axi_lite_ipif.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/family_support.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/ipif_pkg.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/pselect_f.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/slave_attachment.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/vhdl/proc_common_pkg.vhd"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "sources/verilog/cf_clkgen.v"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "Verilog" $file_obj

set file "sources/verilog/user_logic2.v"
set file_obj [get_files -of_objects sources_1 [list "*$file"]]
set_property "file_type" "Verilog" $file_obj

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "../../XilinxIP" $obj
set_property "top" "axi_clkgen" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "axi_clkgen" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]

ipx::package_project -root_dir {../axi_clkgen_v2_00_a}
set_property vendor {kutu.com.au} [ipx::current_core]
set_property library {kutu} [ipx::current_core]
set_property taxonomy {{/Kutu}} [ipx::current_core]
set_property vendor_display_name {Kutu Pty. Ltd.} [ipx::current_core]
set_property company_url {www.kutu.com.au} [ipx::current_core]
set_property value_validation_range_maximum {1} [ipx::get_user_parameter C_MMCM_TYPE [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_hdl_parameter C_MMCM_TYPE [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_user_parameter C_MMCM_TYPE [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_hdl_parameter C_MMCM_TYPE [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_SLV_DWIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_SLV_DWIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_SLV_DWIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_SLV_DWIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_SLV_AWIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_SLV_AWIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_SLV_AWIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_SLV_AWIDTH [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_user_parameter C_NUM_MEM [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_hdl_parameter C_NUM_MEM [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_user_parameter C_NUM_MEM [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_hdl_parameter C_NUM_MEM [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_user_parameter C_NUM_REG [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_hdl_parameter C_NUM_REG [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_user_parameter C_NUM_REG [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_hdl_parameter C_NUM_REG [ipx::current_core]]
set_property value_validation_range_maximum {8} [ipx::get_user_parameter C_DPHASE_TIMEOUT [ipx::current_core]]
set_property value_validation_range_maximum {8} [ipx::get_hdl_parameter C_DPHASE_TIMEOUT [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_user_parameter C_DPHASE_TIMEOUT [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_hdl_parameter C_DPHASE_TIMEOUT [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_user_parameter C_USE_WSTRB [ipx::current_core]]
set_property value_validation_range_maximum {1} [ipx::get_hdl_parameter C_USE_WSTRB [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_user_parameter C_USE_WSTRB [ipx::current_core]]
set_property value_validation_range_minimum {0} [ipx::get_hdl_parameter C_USE_WSTRB [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_S_AXI_ADDR_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_user_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_maximum {32} [ipx::get_hdl_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_user_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property value_validation_range_minimum {1} [ipx::get_hdl_parameter C_S_AXI_DATA_WIDTH [ipx::current_core]]
set_property interface_mode {master} [ipx::get_bus_interface signal_clock [ipx::current_core]]
ipx::create_xgui_files [ipx::current_core]
ipx::save_core [ipx::current_core]
update_ip_catalog -rebuild -repo_path ../../XilinxIP
ipx::check_integrity -quiet [ipx::current_core]
ipx::unload_core {kutu.com.au:kutu:axi_clkgen:1.0}

puts "INFO: Project created:axi_clkgen_v2_00_a"

